### ISSUE TITLE
Value out of range

### ISSUE THREAD

**Issue by firegate666** [thi-ng/punchcard#1]
When I execute it on our repository, it is fine if I limit by author. If I try a full year without author I get

```
Exception in thread "main" java.lang.IllegalArgumentException: Value out of range for byte: 972, compiling:(/private/var/folders/3v/97z0_58s0_g9516pbx390y8w0000gp/T/form-init8852258164093834295.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: Value out of range for byte: 972
	at clojure.lang.RT.byteCast(RT.java:1083)
	at thi.ng.ndarray.core.NDArray2int8.set_at(core.cljc:122)
	at thi.ng.punchcard.core$punch_card$fn__13351.invoke(core.clj:130)
	at thi.ng.punchcard.core$punch_card.invokeStatic(core.clj:130)
	at thi.ng.punchcard.core$punch_card.invoke(core.clj:125)
	at thi.ng.punchcard.core$_main.invokeStatic(core.clj:178)
	at thi.ng.punchcard.core$_main.doInvoke(core.clj:170)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at clojure.lang.Var.invoke(Var.java:430)
	at user$eval5.invokeStatic(form-init8852258164093834295.clj:1)
	at user$eval5.invoke(form-init8852258164093834295.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
```

**Comment by firegate666** [comment]
./punchcard --repo ../frontend --from "2019-01-01 00:00" --to "2019-12-31 23:59"

VS

./punchcard --repo ../frontend --from "2019-01-01 00:00" --to "2019-12-31 23:59" --author "example@example.com"
